In [298]:
import pandas as pd
import numpy as np

In [462]:
df = pd.read_csv('/content/drive/My Drive/FolderBaru/Regresi/RM1_M1_S01_DS1_Linear Regression.csv')
df.shape

(1500, 1)

In [463]:
df = df.astype({'CLIENTNUM;Annual_Income;Age;Average_Monthly_Revenue':'str'})

In [464]:
df.dtypes

CLIENTNUM;Annual_Income;Age;Average_Monthly_Revenue    object
dtype: object

In [465]:
df[['CLIENTNUM','Annual_Income','Age','Average_Monthly_Revenue']] = df['CLIENTNUM;Annual_Income;Age;Average_Monthly_Revenue'].str.split(";",expand=True)
df.drop(columns='CLIENTNUM;Annual_Income;Age;Average_Monthly_Revenue',inplace=True)

In [466]:
df = df.apply(pd.to_numeric, errors='raise')

In [467]:
df.dtypes

CLIENTNUM                    int64
Annual_Income                int64
Age                        float64
Average_Monthly_Revenue    float64
dtype: object

In [468]:
df

CLIENTNUM  Annual_Income        Age  Average_Monthly_Revenue
0        373678          98000  27.225581               127.516737
1        216593          71500  26.586436                91.060867
2        346368          49100  18.338888                 7.843565
3        261066          84000  24.216146                96.206097
4        788167          58000  21.267741                32.920307
...         ...            ...        ...                      ...
1495     105962          58700  28.715240                53.290801
1496     873471          73800  24.675543               106.856612
1497     557439          64600  20.876808                74.440146
1498     136769          50400  26.484840                23.042521
1499     360524          87900  18.033392               127.856234

[1500 rows x 4 columns]

In [469]:
df.corr()['Average_Monthly_Revenue']

CLIENTNUM                 -0.020414
Annual_Income              0.936403
Age                        0.199164
Average_Monthly_Revenue    1.000000
Name: Average_Monthly_Revenue, dtype: float64

In [470]:
y = df['Average_Monthly_Revenue'].values
x = df['Annual_Income'].values

In [471]:
x = x.reshape(-1,1)
x

array([[98000],
       [71500],
       [49100],
       ...,
       [64600],
       [50400],
       [87900]])

In [472]:
from sklearn.model_selection import train_test_split

In [473]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state = 42)

In [311]:
from sklearn.linear_model import LinearRegression

In [312]:
x_train.shape

(1200, 1)

In [313]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [314]:
model.score(x_test,y_test)

0.8551054912625872

In [315]:
model.predict(np.array([2.2]).reshape(-1,1))

array([-81.02223667])

In [316]:
model.intercept_

-81.02708070067396

In [317]:
model.predict(np.array([71500]).reshape(-1,1))

array([76.40376495])

In [318]:
from sklearn.metrics import r2_score

In [336]:
r2_score(y_test, model.predict(x_test))

0.8551054912625872

In [320]:
df['Averge_Montly_Revenue_Estimate'] = model.predict(df['Annual_Income'].values.reshape(-1,1))

In [321]:
df

CLIENTNUM  ...  Averge_Montly_Revenue_Estimate
0        373678  ...                      134.752260
1        216593  ...                       76.403765
2        346368  ...                       27.082773
3        261066  ...                      103.926640
4        788167  ...                       46.679060
...         ...  ...                             ...
1495     105962  ...                       48.220341
1496     873471  ...                       81.467974
1497     557439  ...                       61.211138
1498     136769  ...                       29.945152
1499     360524  ...                      112.513777

[1500 rows x 5 columns]

In [322]:
df.describe()['Average_Monthly_Revenue'].to_frame()

Average_Monthly_Revenue
count              1500.000000
mean                 97.009454
std                  72.698244
min                 -59.205492
25%                  44.321019
50%                  85.178843
75%                 136.920919
max                 445.391560

In [323]:
df[df['Average_Monthly_Revenue'] < 0]

CLIENTNUM  ...  Averge_Montly_Revenue_Estimate
38       149329  ...                       15.413074
53       890519  ...                       20.036917
69       169923  ...                       55.046014
82       919437  ...                       21.798381
102      543344  ...                        7.486486
...         ...  ...                             ...
1453     823657  ...                       10.348865
1459     402618  ...                        2.422277
1469     198309  ...                       75.302850
1472     990396  ...                       10.348865
1491     183987  ...                        3.523192

[88 rows x 5 columns]

In [338]:
df2 = pd.read_csv('/content/drive/My Drive/FolderBaru/Regresi/RM1_M1_S02_DS1_Coefficient_of_Determination.csv')
df2.head()

CLIENTNUM;Annual_Income;Averge_Montly_Revenue;Averge_Montly_Revenue_Estimate
0                          373678;98000;30.85;137.12                          
1                           216593;71500;190.4;78.02                          
2                           346368;49100;40.26;28.07                          
3                          261066;84000;127.56;105.9                          
4                           788167;58000;52.66;47.92

In [339]:
df2[['CLIENTNUM','Annual_Income','Averge_Montly_Revenue','Averge_Montly_Revenue_Estimate']] = df2['CLIENTNUM;Annual_Income;Averge_Montly_Revenue;Averge_Montly_Revenue_Estimate'].str.split(";",expand=True)
df2.drop(columns='CLIENTNUM;Annual_Income;Averge_Montly_Revenue;Averge_Montly_Revenue_Estimate',inplace=True)
df2 = df2.apply(pd.to_numeric, errors='raise')

In [326]:
df2.dtypes

CLIENTNUM                           int64
Annual_Income                       int64
Averge_Montly_Revenue             float64
Averge_Montly_Revenue_Estimate    float64
dtype: object

In [327]:
df2.describe()['Averge_Montly_Revenue'].to_frame()

Averge_Montly_Revenue
count            1500.000000
mean               99.100853
std               110.136949
min                 3.980000
25%                29.385000
50%                55.185000
75%               126.060000
max               745.220000

In [328]:
df2['Difference_of_Two_Columns_Averge_Montly_Revenue_Averge_Montly_Revenue_Estimate'] = df['Average_Monthly_Revenue'] - df['Averge_Montly_Revenue_Estimate']

In [329]:
df2['Square_Difference_of_Two_Columns_Averge_Montly_Revenue_Averge_Montly_Revenue_Estimate'] = df2['Difference_of_Two_Columns_Averge_Montly_Revenue_Averge_Montly_Revenue_Estimate']**2

In [330]:
df2

CLIENTNUM  ...  Square_Difference_of_Two_Columns_Averge_Montly_Revenue_Averge_Montly_Revenue_Estimate
0        373678  ...                                          52.352792                                    
1        216593  ...                                         214.830645                                    
2        346368  ...                                         370.147111                                    
3        261066  ...                                          59.606786                                    
4        788167  ...                                         189.303281                                    
...         ...  ...                                                ...                                    
1495     105962  ...                                          25.709571                                    
1496     873471  ...                                         644.582956                                    
1497     557439  ...                                         175.006654                                    
1498     136769  ...                                          47.646317                                    
1499     360524  ...                                         235.390987                                    

[1500 rows x 6 columns]

In [332]:
df2['Subtract_by_Constant_Averge_Montly_Revenue'] = df2['Averge_Montly_Revenue'] - df2['Averge_Montly_Revenue'].mean()
df2.head()

CLIENTNUM  ...  Subtract_by_Constant_Averge_Montly_Revenue
0     373678  ...                                  -68.250853
1     216593  ...                                   91.299147
2     346368  ...                                  -58.840853
3     261066  ...                                   28.459147
4     788167  ...                                  -46.440853

[5 rows x 7 columns]

In [335]:
df2['Square_Subtract_by_Constant_Averge_Montly_Revenue'] = df2['Subtract_by_Constant_Averge_Montly_Revenue']**2
df2.head()

CLIENTNUM  ...  Square_Subtract_by_Constant_Averge_Montly_Revenue
0     373678  ...                                        4658.178981
1     216593  ...                                        8335.534182
2     346368  ...                                        3462.246021
3     261066  ...                                         809.923029
4     788167  ...                                        2156.752858

[5 rows x 8 columns]

    Create a dummy variable (select variable 'CLIENTNUM', then search function 'If Numeric' and execute)
    Select the columns - If_Numeric_CLIENTNUM, Square_Subtract_by_Constant_Averge_Montly_Revenue, Square_Difference_of_Two_Columns_Averge_Montly_Revenue_Averge_Montly_Revenue_Estimate
    Search for function 'Roll Up'. Fill parameters with following value: (Parameter) -- (Option to choose)
        If_Numeric_CLIENTNUM -- Count Distinct
        Square_Difference_of_Two_Columns_Averge_Montly_Revenue_Averge_Montly_Revenue_Estimate -- Sum 
        Group_By -- If_Numeric_CLIENTNUM
        Square_Subtract_by_Constant_Averge_Montly_Revenue -- Sum
    Select the columns - Sum_Square_Difference_of_Two_Columns_Averge_Montly_Revenue_Averge_Montly_Revenue_Estimate_, Sum_Square_Subtract_by_Constant_Averge_Montly_Revenue
    Search for function 'Ratio of Two Columns' and execute (select 'Sum_Square_Subtract_by_Constant_Averge_Montly_Revenue' as denominator)
    Select the column 'Ratio_of_Two_Columns_Sum_Square_Difference_of_Two_Columns_Averge_Montly_Revenue_Averge_Montly_Revenue_Estimate__Sum_Square_Subtract_by_Constant_Averge_Montly_Revenue'
    Search for function 'Subtract by Constant' and execute (choose the option 'Constant-x' and put 1 as constant)

In [474]:
df2

CLIENTNUM  ...  Averge_Montly_Revenue_Estimate
0        373678  ...                          137.12
1        216593  ...                           78.02
2        346368  ...                           28.07
3        261066  ...                          105.90
4        788167  ...                           47.92
...         ...  ...                             ...
1495     105962  ...                           49.48
1496     873471  ...                           83.15
1497     557439  ...                           62.64
1498     136769  ...                           30.97
1499     360524  ...                          114.60

[1500 rows x 4 columns]

In [477]:
x = df2.Annual_Income.values
y = df2.Averge_Montly_Revenue.values

In [478]:
x = x.reshape(-1,1)

In [483]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y,train_size=0.9, random_state = 42)

In [484]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [485]:
y_pred = model.predict(X_test)

In [481]:
model.score(x_test,y_test)

0.8537070822282795

In [487]:
r2_score(Y_test,y_pred)

0.4094855839482172

In [488]:
model.intercept_

-81.42608216216006