In [216]:
import numpy as np
import pandas as pd

In [217]:
df = pd.read_excel('/content/drive/My Drive/FolderBaru/Latihan Regresi.xlsx')

In [218]:
df.dropna(inplace=True) #Menghapus Missing values

In [219]:
df

Hp  Baterai  Kamera  Harga
0  A1       21       8    7.0
1  A2       16       2    3.0
2  A3       17       6    7.0
4  A5       20       4    2.0
6  A7       22       7    8.0
7  A8       18       3    3.0

In [220]:
x = np.array([(df['Baterai']),(df['Kamera'])])
x.shape

(2, 6)

In [221]:
np.ones([1,6])

array([[1., 1., 1., 1., 1., 1.]])

In [222]:
x

array([[21, 16, 17, 20, 22, 18],
       [ 8,  2,  6,  4,  7,  3]])

In [223]:
x_baru = np.vstack((np.ones([1,6]),x))
x_baru = x_baru.T
x_baru

array([[ 1., 21.,  8.],
       [ 1., 16.,  2.],
       [ 1., 17.,  6.],
       [ 1., 20.,  4.],
       [ 1., 22.,  7.],
       [ 1., 18.,  3.]])

In [224]:
y = df['Harga']
y_baru = np.array(y).reshape(-1,1)
y_baru

array([[7.],
       [3.],
       [7.],
       [2.],
       [8.],
       [3.]])

In [225]:
w = np.linalg.inv(x_baru.T@x_baru)@x_baru.T@y_baru
w

array([[ 6.125     ],
       [-0.38541667],
       [ 1.23958333]])

In [226]:
e = w[0]
w_baru = np.array(w[1:]).reshape(1,2)
print(e)
print(w_baru)
x_test = np.array([14,9])
print(x_test)

[6.125]
[[-0.38541667  1.23958333]]
[14  9]


In [227]:
prediksi = w_baru@x_test + e
prediksi

array([11.88541667])

In [228]:
from sklearn import linear_model

In [229]:
model =linear_model.LinearRegression()

In [230]:
model.fit(x_baru,y_baru)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [235]:
model.fit(x.T,y) #fase training
print('Coefficient : ' + str(model.coef_))
print('Intercept : ' + str(model.intercept_))

Coefficient : [-0.38541667  1.23958333]
Intercept : 6.125000000000005


In [ ]:
x_test = [[14,9]]
np.array(x_test)

array([[14,  9]])

In [ ]:
np.array((14,9)).reshape(1,2)

array([[14,  9]])

In [ ]:
model.predict(x_test)

array([11.88541667])