In [189]:
import pandas as pd
import numpy as np

In [190]:
df = pd.read_csv('/content/drive/My Drive/FolderBaru/Regresi/RM1_M2_S01_DS1_Multiple_Linear_Regression.csv')
df.head()

ArrivalDelay;AirTime;DepartureDelay;Distance;TaxiIn;TaxiOut;MidOfWeekFlag
0                               37;69;48;525;28;11;0                       
1                               -8;72;-2;535;29;10;0                       
2                               65;69;75;529;62;10;0                       
3                                43;75;51;535;9;15;0                       
4                               -3;70;-1;513;22;17;0

In [191]:
df[['ArrivalDelay','AirTime','DepartureDelay','Distance','TaxiIn','TaxiOut','MidOfWeekFlag']] = df['ArrivalDelay;AirTime;DepartureDelay;Distance;TaxiIn;TaxiOut;MidOfWeekFlag'].str.split(";", expand=True)
df.drop(columns='ArrivalDelay;AirTime;DepartureDelay;Distance;TaxiIn;TaxiOut;MidOfWeekFlag',inplace=True)
df.head()

ArrivalDelay AirTime DepartureDelay Distance TaxiIn TaxiOut MidOfWeekFlag
0           37      69             48      525     28      11             0
1           -8      72             -2      535     29      10             0
2           65      69             75      529     62      10             0
3           43      75             51      535      9      15             0
4           -3      70             -1      513     22      17             0

In [192]:
df = df.apply(pd.to_numeric, errors='raise')

In [193]:
df.describe()

ArrivalDelay       AirTime  ...       TaxiOut  MidOfWeekFlag
count  26541.000000  26541.000000  ...  26541.000000   26541.000000
mean       6.294299    130.743793  ...     16.830677       0.246034
std       23.553876     83.827445  ...      8.011355       0.430707
min      -58.000000     32.000000  ...      1.000000       0.000000
25%       -8.000000     58.000000  ...     11.000000       0.000000
50%        0.000000     91.000000  ...     15.000000       0.000000
75%       13.000000    204.000000  ...     20.000000       0.000000
max      120.000000    458.000000  ...    142.000000       1.000000

[8 rows x 7 columns]

In [194]:
df.corr()['ArrivalDelay'].to_frame()

ArrivalDelay
ArrivalDelay        1.000000
AirTime            -0.065298
DepartureDelay      0.898386
Distance           -0.089080
TaxiIn              0.005806
TaxiOut             0.272428
MidOfWeekFlag       0.010969

In [195]:
y = df['ArrivalDelay']
x = df[df.columns[1:]].values

In [196]:
y.shape

(26541,)

In [197]:
from sklearn.model_selection import train_test_split

In [198]:
x_train, x_test, y_train, y_test = train_test_split(x,y, train_size = 0.8, random_state=42)

In [199]:
from sklearn.linear_model import LinearRegression

In [200]:
lm = LinearRegression()
lm.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [201]:
print('Coefficient : ' + str(lm.coef_))
print('Intercept : ' + str(lm.intercept_))

Coefficient : [ 3.72923568e-01  9.36284125e-01 -4.79147250e-02  3.36625122e-04
  7.29882443e-01 -7.40667674e-01]
Intercept : -18.96890760968754


In [202]:
y_pred = lm.predict(x_test)

In [203]:
y_pred

array([ -4.67587559,  -3.16017906,  54.34430718, ...,  18.22536243,
       -12.64039029,  30.37870758])

In [206]:
x_test[0]

array([ 48,  -4, 302,  31,  20,   0])

In [207]:
#import pandas as pd
# import numpy as np
# from sklearn import datasets, linear_model
# from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from scipy import stats

# diabetes = datasets.load_diabetes()
# X = diabetes.data
# y = diabetes.target

X2 = sm.add_constant(x)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())


                            OLS Regression Results                            
Dep. Variable:           ArrivalDelay   R-squared:                       0.920
Model:                            OLS   Adj. R-squared:                  0.920
Method:                 Least Squares   F-statistic:                 5.119e+04
Date:                Fri, 28 Aug 2020   Prob (F-statistic):               0.00
Time:                        11:40:48   Log-Likelihood:                -87914.
No. Observations:               26541   AIC:                         1.758e+05
Df Residuals:                   26534   BIC:                         1.759e+05
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -19.0433      0.158   -120.585      0.0

In [209]:
x = df[df.columns.delete(4)[1:]].values
y = df['ArrivalDelay']

In [210]:
x_train, x_test, y_train, y_test = train_test_split(x,y, train_size = 0.8, random_state=42)

In [211]:
lm.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [212]:
print('Coefficient : ' + str(lm.coef_))
print('Intercept : ' + str(lm.intercept_))

Coefficient : [ 0.37291974  0.93628531 -0.04791435  0.72988473 -0.74066384]
Intercept : -18.955377070717205


In [213]:
lm.score(x_test, y_test)

0.9212603271582992

In [228]:
lm.predict(x_test).shape

(5309,)

In [220]:
x_test[0]

array([ 48,  -4, 302,  20,   0])

In [258]:
x = np.array([0, -1, 0, 0, 0]).reshape(1,-1)

In [259]:
lm.predict(x)

array([-19.89166238])

In [241]:
df

ArrivalDelay  AirTime  DepartureDelay  ...  TaxiIn  TaxiOut  MidOfWeekFlag
0                37       69              48  ...      28       11              0
1                -8       72              -2  ...      29       10              0
2                65       69              75  ...      62       10              0
3                43       75              51  ...       9       15              0
4                -3       70              -1  ...      22       17              0
...             ...      ...             ...  ...     ...      ...            ...
26536            -3      238              -7  ...      43       17              0
26537            56      243              55  ...     106       15              0
26538             1      235              -8  ...      37       24              0
26539            65      231              70  ...      74       18              0
26540            26      245              21  ...      37       15              0

[26541 rows x 7 columns]

In [260]:
from scipy.stats import zscore

In [269]:
z_score = df.drop(columns=['TaxiIn','MidOfWeekFlag']).apply(zscore)

In [270]:
df.head()

ArrivalDelay  AirTime  DepartureDelay  ...  TaxiIn  TaxiOut  MidOfWeekFlag
0            37       69              48  ...      28       11              0
1            -8       72              -2  ...      29       10              0
2            65       69              75  ...      62       10              0
3            43       75              51  ...       9       15              0
4            -3       70              -1  ...      22       17              0

[5 rows x 7 columns]

In [282]:
z_score['ArrivalDelay'].max()

4.827563896967631

In [283]:
from scipy import stats
df[(np.abs(stats.zscore(df)) < 3).all(axis=1)]

ArrivalDelay  AirTime  DepartureDelay  ...  TaxiIn  TaxiOut  MidOfWeekFlag
0                37       69              48  ...      28       11              0
1                -8       72              -2  ...      29       10              0
2                65       69              75  ...      62       10              0
3                43       75              51  ...       9       15              0
4                -3       70              -1  ...      22       17              0
...             ...      ...             ...  ...     ...      ...            ...
26535           -11      222              -7  ...      57       24              1
26536            -3      238              -7  ...      43       17              0
26538             1      235              -8  ...      37       24              0
26539            65      231              70  ...      74       18              0
26540            26      245              21  ...      37       15              0

[25002 rows x 7 columns]

In [ ]:
stats.zscore(df)